language: java

matrix:
  include:
  - jdk: oraclejdk8
    env: JAVA_VERSION=8
  - jdk: oraclejdk11
    env: JAVA_VERSION=11

cache:
  directories:
  - $HOME/.m2

#check coverage
before_script:
  - "mvn com.coveo:fmt-maven-plugin:check"
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys

script:
  - ./.run-travis.sh
